In [1]:
import pandas as pd

In [28]:
train = pd.read_csv('train.csv').fillna(0)
print(train.axes)
def SexToNum(dfTemp):
    if dfTemp['Sex'] == 'male':
        return 0
    if dfTemp['Sex'] == 'female':
        return 1

def EmbarkedToNum(dfTemp):
    if dfTemp['Embarked'] == 'C':
        return 0
    elif dfTemp['Embarked'] == 'S':
        return 1
    elif dfTemp['Embarked'] == 'Q':
        return 2
    else:
        return 3
df_train['PassengerId'] = train['PassengerId']
df_train['Pclass'] = train['Pclass']
df_train['Age'] = train['Age']
df_train['SibSp'] = train['SibSp']
df_train['Parch'] = train['Parch']
df_train['Fare'] = train['Fare']
df_train['Sex'] = train.apply(SexToNum, axis=1)
df_train['Survived'] = train['Survived']

[RangeIndex(start=0, stop=891, step=1), Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')]

In [26]:
df

     Sex  PassengerId  Pclass   Age  SibSp  Parch      Fare  Survived
0      0            1       3  22.0      1      0    7.2500         0
1      1            2       1  38.0      1      0   71.2833         1
2      1            3       3  26.0      0      0    7.9250         1
3      1            4       1  35.0      1      0   53.1000         1
4      0            5       3  35.0      0      0    8.0500         0
5      0            6       3   0.0      0      0    8.4583         0
6      0            7       1  54.0      0      0   51.8625         0
7      0            8       3   2.0      3      1   21.0750         0
8      1            9       3  27.0      0      2   11.1333         1
9      1           10       2  14.0      1      0   30.0708         1
10     1           11       3   4.0      1      1   16.7000         1
11     1           12       1  58.0      0      0   26.5500         1
12     0           13       3  20.0      0      0    8.0500         0
13     0           14       3  39.0      1      5   31.2750         0
14     1           15       3  14.0      0      0    7.8542         0
15     1           16       2  55.0      0      0   16.0000         1
16     0           17       3   2.0      4      1   29.1250         0
17     0           18       2   0.0      0      0   13.0000         1
18     1           19       3  31.0      1      0   18.0000         0
19     1           20       3   0.0      0      0    7.2250         1
20     0           21       2  35.0      0      0   26.0000         0
21     0           22       2  34.0      0      0   13.0000         1
22     1           23       3  15.0      0      0    8.0292         1
23     0           24       1  28.0      0      0   35.5000         1
24     1           25       3   8.0      3      1   21.0750         0
25     1           26       3  38.0      1      5   31.3875         1
26     0           27       3   0.0      0      0    7.2250         0
27     0           28       1  19.0      3      2  263.0000         0
28     1           29       3   0.0      0      0    7.8792         1
29     0           30       3   0.0      0      0    7.8958         0
..   ...          ...     ...   ...    ...    ...       ...       ...
861    0          862       2  21.0      1      0   11.5000         0
862    1          863       1  48.0      0      0   25.9292         1
863    1          864       3   0.0      8      2   69.5500         0
864    0          865       2  24.0      0      0   13.0000         0
865    1          866       2  42.0      0      0   13.0000         1
866    1          867       2  27.0      1      0   13.8583         1
867    0          868       1  31.0      0      0   50.4958         0
868    0          869       3   0.0      0      0    9.5000         0
869    0          870       3   4.0      1      1   11.1333         1
870    0          871       3  26.0      0      0    7.8958         0
871    1          872       1  47.0      1      1   52.5542         1
872    0          873       1  33.0      0      0    5.0000         0
873    0          874       3  47.0      0      0    9.0000         0
874    1          875       2  28.0      1      0   24.0000         1
875    1          876       3  15.0      0      0    7.2250         1
876    0          877       3  20.0      0      0    9.8458         0
877    0          878       3  19.0      0      0    7.8958         0
878    0          879       3   0.0      0      0    7.8958         0
879    1          880       1  56.0      0      1   83.1583         1
880    1          881       2  25.0      0      1   26.0000         1
881    0          882       3  33.0      0      0    7.8958         0
882    1          883       3  22.0      0      0   10.5167         0
883    0          884       2  28.0      0      0   10.5000         0
884    0          885       3  25.0      0      0    7.0500         0
885    1          886       3  39.0      0      5   29.1250         0
886    0          887       2  27.0      0      0   13.0000         0
887    1          888       1  19.0      0      0   30.0000         1
888    1          889       3   0.0      1      2   23.4500         0
889    0          890       1  26.0      0      0   30.0000         1
890    0          891       3  32.0      0      0    7.7500         0

[891 rows x 8 columns]

In [ ]:
train = pd.read_csv('test.csv').fillna(0)
print(train.axes)
def SexToNum(dfTemp):
    if dfTemp['Sex'] == 'male':
        return 0
    if dfTemp['Sex'] == 'female':
        return 1

def EmbarkedToNum(dfTemp):
    if dfTemp['Embarked'] == 'C':
        return 0
    elif dfTemp['Embarked'] == 'S':
        return 1
    elif dfTemp['Embarked'] == 'Q':
        return 2
    else:
        return 3
df_test['PassengerId'] = train['PassengerId']
df_test['Pclass'] = train['Pclass']
df_test['Age'] = train['Age']
df_test['SibSp'] = train['SibSp']
df_test['Parch'] = train['Parch']
df_test['Fare'] = train['Fare']
df_test['Sex'] = train.apply(SexToNum, axis=1)
df_test['Survived'] = train['Survived']